# Generated by Django 4.2 on 2024-08-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('detail', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('detail', models.CharField(max_length=40)),
                ('done', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoDate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('detail', models.CharField(max_length=40)),
                ('frequency', models.CharField(choices=[('D', 'Diaria'), ('W', 'Semanal'), ('M', 'Mensual'), ('A', 'Anual')], max_length=1)),
                ('freq_data', models.CharField(max_length=5)),
                ('done', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
